version: '3.8'

services:
  wa_bot_service:
    build: .
    env_file:
      - .env
    container_name: wa_bot_service
    restart: always
    depends_on:
      - em_services_master_db
      - redis
    volumes:
      - .:/opt/wa_bot_service
      # :/opt/wa_bot_service/data
      - ../media_storage:/opt/media_storage
    networks:
      - em_services_network

  em_services_master_db:
    image: postgres:latest
    container_name: em_services_master_db
    environment:
      - POSTGRES_DB=lekhakaar
      - POSTGRES_USER=fabnest-test
      - POSTGRES_PASSWORD=fabnest-test
      # - POSTGRES_REPLICATION_MODE=master
      # - POSTGRES_REPLICATION_USER=replica_user
      # - POSTGRES_REPLICATION_PASSWORD=replica_password
    networks:
      - em_services_network
    ports:
      - 5432:5432
    volumes:
      - em_services_db_data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - em_services_network

volumes:
  em_services_db_data:
  media_storage:

networks:
  em_services_network: