// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/wa_grpc_service.proto

package wa_grpc_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WAService_SendOtpMessage_FullMethodName = "/WAService/SendOtpMessage"
)

// WAServiceClient is the client API for WAService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WAServiceClient interface {
	SendOtpMessage(ctx context.Context, in *SendOtpRequest, opts ...grpc.CallOption) (*SendOtpResponse, error)
}

type wAServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWAServiceClient(cc grpc.ClientConnInterface) WAServiceClient {
	return &wAServiceClient{cc}
}

func (c *wAServiceClient) SendOtpMessage(ctx context.Context, in *SendOtpRequest, opts ...grpc.CallOption) (*SendOtpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendOtpResponse)
	err := c.cc.Invoke(ctx, WAService_SendOtpMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WAServiceServer is the server API for WAService service.
// All implementations must embed UnimplementedWAServiceServer
// for forward compatibility.
type WAServiceServer interface {
	SendOtpMessage(context.Context, *SendOtpRequest) (*SendOtpResponse, error)
	mustEmbedUnimplementedWAServiceServer()
}

// UnimplementedWAServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWAServiceServer struct{}

func (UnimplementedWAServiceServer) SendOtpMessage(context.Context, *SendOtpRequest) (*SendOtpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendOtpMessage not implemented")
}
func (UnimplementedWAServiceServer) mustEmbedUnimplementedWAServiceServer() {}
func (UnimplementedWAServiceServer) testEmbeddedByValue()                   {}

// UnsafeWAServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WAServiceServer will
// result in compilation errors.
type UnsafeWAServiceServer interface {
	mustEmbedUnimplementedWAServiceServer()
}

func RegisterWAServiceServer(s grpc.ServiceRegistrar, srv WAServiceServer) {
	// If the following call pancis, it indicates UnimplementedWAServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WAService_ServiceDesc, srv)
}

func _WAService_SendOtpMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendOtpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WAServiceServer).SendOtpMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WAService_SendOtpMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WAServiceServer).SendOtpMessage(ctx, req.(*SendOtpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WAService_ServiceDesc is the grpc.ServiceDesc for WAService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WAService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "WAService",
	HandlerType: (*WAServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendOtpMessage",
			Handler:    _WAService_SendOtpMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/wa_grpc_service.proto",
}
